config/routes.rb
Welcometothesocial::Application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  root 'pages#index'
  
  match  '/boards/personal', to: 'boards#personal', via: 'get', as: :personal
  match  '/boards/discover', to: 'boards#discover', via: 'get', as: :discover
  match  '/boards/:id/love', to: 'boards#love', via: 'get', as: :love
  match  '/boards/:id/unlove', to: 'boards#unlove', via: 'get', as: :unlove
  match  '/replies/new', to: 'replies#new', via: 'get'
  match  '/replies/show/:id', to: 'replies#show', via: 'get', as: :replies
  resources :boards do
    resources :posts do
      resources :replies
    end
  end
  

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :users
  has_many :posts
  validates :name, uniqueness: true
  
    # Override default find method to use slug rather than id
  def self.find(name)
    find_by_name(name)
  end

  # Change default param for board from id to slug
  def to_param
    name
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    identity = find_by(provider: auth.provider, uid: auth.uid)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :board
  has_one :user
  has_many :replies
end

app/models/posts.rb
class Posts < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
end

app/models/replies.rb
class Replies < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  def self.getreplycount(post)
    Replies.where('post_id == ? AND content != ?', post, "NULL").count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  has_many :posts
  has_many :boards
  has_many :replies
  
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      
      if registered_user
        return registered_user
      else
        user = User.create(
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20]
         )
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    personal_path
  end
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  def personal
    if !signed_in?
      return redirect_to root_path
    end
    @user = User.find(current_user)
    @boards = Board.where('name != ? AND user_id == ?', "NULL", @user.id)
    @posts = Post.where('title != ? AND user_id == ?', "NULL", @user.id)
  end
  
  def show
    @board = Board.find(params[:id])
    @boardname = @board.name
    @user = User.find(current_user.id) rescue 0
    @boarddescription = @board.description
    @posts = @board.posts.where('title != ? AND content != ?', "NULL", "NULL")
  end
  
  def new
    @user = User.find(current_user.id)
    @board = @user.boards.new
  end
  
  def create
    @user = User.find(current_user.id)
    @board = @user.boards.new
    @board[:name] = params[:boardform][:name]
    @board[:description] = params[:boardform][:description]
    if @board.save
      return redirect_to board_path(@board.name)
    else
      return redirect_to new_board_path
    end
  end
  
  def discover
    @boards = Board.where('name != ?', "NULL")
  end
  
  def love
    @board = Board.find(params[:id])
    @user = User.find(current_user.id)
    @board[:user_id] = @user.id
    @board.save!
    return redirect_to board_path(params[:id])
  end
  
  def unlove
    @board = Board.find(params[:id])
    @user = User.find(current_user.id)
    if @board.user_id == @user.id
      @board.user_id = 0
    else
    @board.user_id.delete(@user.id)
    end
    @board.save!
    return redirect_to board_path(params[:id])
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
     
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    if signed_in?
      return redirect_to personal_path
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @board = Board.find(params[:board_id])
    @post = @board.posts.new
  end
  
  def create
    @board = Board.find(params[:board_id])
    @post = @board.posts.new
    @post[:title] = params[:postform][:title]
    @post[:content] = params[:postform][:content]
    @post[:user_id] = current_user.id
    if @post.save
      return redirect_to board_post_path(@board.name, @post.id)
    else
      return redirect_to new_board_post_path(@board.name)
    end
  end
  
  def show
    @board = Board.find(params[:board_id])
    @post = @board.posts.find(params[:id])
    @replies = Replies.where('post_id == ? AND content != ?', @post.id, "NULL")
  end
  
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @board = Board.find(params[:board_id])
    @post = @board.posts.find(params[:id])
  end

  def create
    @reply = Replies.new
    @reply[:post_id] = params[:post_id]
    @reply[:user_id] = current_user.id
    @reply[:content] = params[:replyform][:content]
    if @reply.save
      return redirect_to board_post_path(params[:board_id], params[:post_id])
    else
      return redirect_to board_post_path(params[:board_id], params[:post_id])
    end
  end
  
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, :finish_signup

  def signin
  end

  def finish_signup
    if request.patch? && params[:user] #&& params[:user][:email]
      if current_user.update(user_params)
        current_user.skip_reconfirmation!
        sign_in(current_user, :bypass => true)
        redirect_to current_user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/boards/discover.html.erb
<h1 class="pagetitle"> Discover </h1>
<div  class="pagecontent">
<row>
  <div class="col-sm-9" style="min-height: 350px;">
    <div class="list-group">
      <% @boards.each do |x| %>
      <%= link_to x, class: "list-group-item" do %>
          <h4 class="list-group-item-heading"><%= x.name %></h4>
          <p class="list-group-item-text"><%= x.description %></p>
        <% end %>
    <% end %>
    </div>
  </div>
    <div class="col-sm-3" style="margin-top: 125px;">
    <p>Find a board you like, and then click the <i class="fa fa-heart-o"></i> once there to save it to your personal page for later</p>
      <p> Don't like anything you see here? Why not <%= link_to "create your own board!", new_board_path %></p>
  </div>
</row>
</div>

app/views/boards/new.html.erb
<h1 class="pagetitle"> New Board </h1>

<div class="mainsplash center">
  <h2 align="center" style="color: #ccc"> Add a new board </h2>
  <br/>
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for :boardform, url: boards_path do |f| %>
      <%= f.text_field :name, class: "form-control", placeholder: "Board title" %>
      <br/>
      <%= f.text_area :description, class: "form-control", placeholder: "Board description" %>
      <br/>
      <%= f.submit "Create this board", class: 'btn btn-large btn-primary'%>
    <% end %>
  </div>
</div>

app/views/boards/personal.html.erb
<h1 class="pagetitle"> Personal </h1>
<div  class="pagecontent">
<row>
  <div class="col-sm-8 col-sm-offset-2" align="center">
<!-- check if the user has any posts -->
<% if @posts.empty? %>
<h3> You don't have any recent posts </h3>
<% else %>
        <row>
   <div class="col-sm-3" style="margin-top: 5px;">
         <p>Here's your list of recent posts.</p>
  </div>
  <div class="col-sm-9" style="min-height: 150px;">
    <div class="list-group">
  <% @posts.each do |x| %>
    <%= link_to x.title, board_post_path(x.board, x.id), class: 'list-group-item' %>
<% end %>
    </div>
      </div>
    </row>
<% end %>
<br/>
    <br/>
    <br/>
<!-- check if the user has any boards -->
    <% if @boards.empty? %>
<h3> You aren't a member of any boards </h3>
    <br/>
    <br/>
    <h4><%= link_to "Go discover some new boards!", discover_path %></h4>
<% else %>
    <row>
   <div class="col-sm-3" style="margin-top: 5px;">
    <p>Here's your list of boards you love.</p>
      <p> Don't like anything you see here? <%= link_to "Go discover some new boards!", discover_path %></p>
  </div>
  <div class="col-sm-9" style="min-height: 150px;">
    <div class="list-group">
    <% @boards.each do |x| %>
      <%= link_to x.name, x, class: 'list-group-item' %>
<% end %>
    </div>
      </div>
    </row>
<% end %>
  </div>
  </row>
</div>

app/views/boards/show.html.erb
<h1 class="pagetitle"> <%= @boardname %> </h1>

<div class="lovebutton">
  <% if @user == 0 %>
<% elsif @board.user_id.to_s.include?(@user.id.to_s) %>
  <%= link_to unlove_path do %>
  <i class="fa fa-heart"></i>
  <% end %>
  <% else %>
  <%= link_to love_path do %>
  <i class="fa fa-heart-o"></i>
  <% end %>
  <% end %>
</div>
  
<div  class="pagecontent">
<row>
  <div class="col-sm-9" style="min-height: 350px;">
    <% if @posts.empty? %>
    <h3> No posts yet, <%= link_to "be the first!", new_board_post_path(@board.name) %> </h3>
    <% end %>
    <div class="list-group">
      <% @posts.each do |x| %>
      <%= link_to board_post_path(@board.name, x.id), class: "list-group-item" do %>
      <%= x.title %>
      <span class="badge"><%= Replies.getreplycount(x.id)%> replies</span>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-3" style="margin-top: 50px;">
    <p> <%= @boarddescription %> </p>
    <%= link_to "Add a post", new_board_post_path(@board.name) %>
  </div>
  </row>
</div>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
          <%= link_to ".S", root_path, class: 'navbar-brand' %>
		    </div>
		    <div class="collapse navbar-collapse">
		      <ul class="login nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li><%= link_to discover_path do %><i class="fa fa-search" style="font-size: 18px"></i><% end %></li>
            <li><%= link_to personal_path do %><i class="fa fa-home" style="font-size: 18px"></i><% end %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cogs" style="font-size: 18px"></i></a>
          <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Edit profile", edit_user_registration_path%></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
              <% else %>
                <li><%= link_to('Sign Up', new_user_registration_path) %></li>
              <li><%= link_to('Sign In', new_user_session_path) %></li>
              <% end %>
		      </ul>
		    </div><!--/.nav-collapse -->
		  </div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcometothe.social</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
    <%= render partial: 'layouts/navbar' %> <!-- render the layouts/_navbar.html.erb file so this page isnt so messy -->
		<div class="container">

      
		<%= yield %>
            
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

		</div><!-- /.container -->
</body>
</html>

app/views/pages/index.html.erb
<div class="mainsplash">
<h1 class="mainsplashtitle"> Welcome to the .Social </h1>
</div>
<div class="divider1">
  <row>
    <div class="col-sm-6">
  <h2> .Social basics </h2>
  <p> The .Social is a new way to communicate and share anything and everything in a quick, simple way.</p>
    </div>
    <div class="col-sm-6">
      <%= image_tag "chalkboard101.png", style: 'width: 95%' %>
    </div>
  </row>
</div>
<span class="fa  fa-arrow-down  col-sm-offset-6" style="font-size: 90px;margin-top: 40px;margin-bottom: 40px;"></span>
<div class="divider2">
  <row>
    <div class="col-sm-6">
      <span style="font-size: 120px;margin-left: 50px;" class="fa fa-tachometer">&nbsp;</span>
    </div>
    <div class="col-sm-6">
  <h2> .Social benefits </h2>
        <p> Quick forums, fast posting, easy replies... just some of the .Social benifits avaiable to all .Socialites.</p>
    </div>
  </row>
</div>
<span class="fa  fa-arrow-down  col-sm-offset-6" style="font-size: 90px;margin-top: 15px;margin-bottom: 30px;"></span>
<div class="divider3">
  <row>
    <div class="col-sm-6">
  <h2> .Social future </h2>
  <p> Once you get started you'll be joining an amazing new community spreading .Social worldwide. Get ready for the future, it's happening right here.</p>
    </div>
    <div class="col-sm-6">
      <span style="font-size: 120px;margin-left: 50px;" class="fa fa-rocket">&nbsp;</span>
    </div>
  </row>
</div>
<span class="fa  fa-arrow-down  col-sm-offset-6" style="font-size: 90px;margin-top: 15px;margin-bottom: 20px;"></span>
<div class="getstarted">
  <%= link_to "Lets start", new_user_registration_path, class: "btn btn-large btn-primary col-sm-offset-6" %>
</div>
</div>
		<div id="footerwrap">
			<div class="container">
				<h4>Crafted by <a href="mailto: ccnppro@yahoo.com">Michael Rickert</a> + <a href="mailto: andrew@primefour.com">Andrew Villarrubia</a> + <a href="mailto: transparentb@gmail.com">Skew</a> - Copyright 2014</h4>
			</div>
		</div>

app/views/posts/new.html.erb
<h1 class="pagetitle"> New Post </h1>

<div class="mainsplash center">
  <h2 align="center" style="color: #ccc"> Add a new post to <span style="color: #28D2DE;"><%= @board.name %></span> </h2>
  <br/>
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for :postform, url: board_posts_path(@board.name, @post.id) do |f| %>
      <%= f.text_field :title, class: "form-control", placeholder: "Post title" %>
      <br/>
      <%= f.text_area :content, class: "form-control", placeholder: "Post content" %>
      <br/>
      <%= f.submit "Submit post", class: 'btn btn-large btn-primary'%>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1 class="pagetitle"> View Post </h1>

  <div class="backbutton">
    <%= link_to board_path(@board.name) do %>
    <i class="fa fa-caret-square-o-left"></i>
    <% end %>
  </div>

<div class="pagecontent">
  <div class=" col-sm-8 col-sm-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading postbackground">
      <%= @post.title %>
    </div>
    <div class="panel-body" style="text-align: left">
  <%= @post.content %>
    </div>
  </div>
  </div>
  <div class="col-sm-8 col-sm-offset-2">
  <h3> Replies </h3>
  <% if !@replies.nil? %>
    <div class="list-group">
    <% @replies.each do |x|%>
      <%= link_to nil, class: "list-group-item", style: "text-align: left" do %>
      <span style="float: left; font-size: 8px;margin-right: 10px;"><%= User.find(x.user_id).email %><br/><%= time_ago_in_words(x.created_at) %> ago</span>
      <%= x.content %>
      <% end %>
  <% end %>
    </div>
  <% else %>
  <h5> No replies </h5>
  <% end %>
  </div>
</div>
  <div class="col-sm-12 replybackground">
  <div class="col-sm-6 col-sm-offset-3">
    <% if signed_in? %>
      <%= render replies_new_path %>
    <% end %>
  </div>
  </div>

app/views/replies/_new.html.erb
    <%= form_for :replyform, url: board_post_replies_path(@board.name, @post.id) do |f| %>
<%= f.text_area :content, class: "form-control", placeholder: "Enter your reply here" %>
      <br/>
    <%= f.submit "Submit reply", class: 'btn btn-small btn-primary'%>
    <% end %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/sign_in.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render "devise/shared/links" %>